version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT:-5001}:5000"
    volumes:
      - ./resources:/app/resources
      - ./static:/app/static
    environment:
      - FLASK_ENV=development
      - EPG_XML_PATH=https://epgshare01.online/epgshare01/epg_ripper_ES1.xml.gz
    restart: unless-stopped
  acestream-http-proxy:
    image: "${ACESTREAM_IMAGE}" ghcr.io/martinbjeldbak/acestream-http-proxy
    container_name: acestream-http-proxy
    restart: unless-stopped
    #Descomentar las siguientes líneas si quieres permitir la ejecución desde internet. En caso contrario, solo funcionará en tu red local 
    #environment:
    #  - ALLOW_REMOTE_ACCESS=yes
    ports:
      - "${PORTACE:-6878}:6878"

# Definición de variables de entorno con detección automática de arquitectura
# Este bloque usa un pequeño truco de Docker para evaluar la arquitectura al vuelo
x-architecture-setup: &architecture-setup
  ACESTREAM_IMAGE: >
    ${ACESTREAM_IMAGE:-$(
      case $(uname -m) in
        armv7l|armv7|aarch64) echo "futebas/acestream-engine-arm" ;;
        *)      echo "asopaipa/acestream-http-proxy" ;;
      esac
    )}
